# action.yml
name: 'Python wheels manylinux build'
author: 'Ralf Gabriels'
description: 'Build manylinux wheels for a Python package'
inputs:
  py-version:
    description: 'python version to target (e.g. 3.9)'
    required: true
    default: '3.9'
  py-pep-425:
    description: 'Python version used to install tools (e.g. cp39-cp39)'
    required: true
    default: 'cp39-cp39'
  system-packages:
    description: 'yum packages to install, space-separated'
    required: false
    default: ''
  pre-build-command:
    description: 'command to run before build, e.g. the execution of a script to perform additional build-environment setup'
    required: false
    default: ''
  package-path:
    description: 'path to python package to build, relative to repository root'
    required: false
    default: ''
outputs:
  wheels:
    description: 'Compiled wheel files'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.py-version }}
    - ${{ inputs.py-pep-425 }}
    - ${{ inputs.system-packages }}
    - ${{ inputs.pre-build-command }}
    - ${{ inputs.package-path }}
branding:
  icon: 'package'
  color: 'green'
