name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.9
            pep-425-tag: 'cp39-cp39'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Checkout rustfrc
      uses: actions/checkout@v2
      with:
        repository: tmtenbrink/rustfrc
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build manylinux Python wheels
      uses: './'
      with:
        python-install: "python${{ matrix.python-version }}"
        python-versions: ${{ matrix.pep-425-tag }}
        pre-build-command: 'echo Hello world! Testing pre-build command'
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: 'dist/*-manylinux2014_x86_64.whl'
