name: test

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
          include:
            - py-version: 3.7
              py-pep-425: 'cp37-cp37m'
            - py-version: 3.8
              py-pep-425: 'cp38-cp38'
            - py-version: 3.9
              py-pep-425: 'cp39-cp39'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Checkout rustfrc
      uses: actions/checkout@v2
      with:
        repository: tmtenbrink/rustfrc
        path: test
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py-version }}
    - name: Build manylinux Python wheels
      uses: './'
      with:
        py-version: ${{ matrix.py-pep-425 }}
        py-pep-425: "python${{ matrix.py-version }}"
        package-path: 'test'
    - uses: actions/upload-artifact@v2
      with:
        name: wheels-manylinux
        path: test/dist
