name: test

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Checkout rustfrc
      uses: actions/checkout@v2
      with:
        repository: tmtenbrink/rustfrc
        path: test
    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Build manylinux Python wheels
      uses: './'
      with:
        python-install: 'cp39-cp39'
        python-targets: "python3.9 python3.8 python3.7"
        package-path: 'test'
    - uses: actions/upload-artifact@v2
      with:
        name: wheels-manylinux
        path: test/dist
